# Generated by Django 4.1.5 on 2023-02-18 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auen', '0002_playlist_users_delete_songs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True)),
                ('artist', models.CharField(max_length=50)),
                ('album', models.CharField(max_length=50)),
            ],
        ),
    ]
